name: Unit tests
on:
  - pull_request

jobs:
  Linting:
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pytest
        run: python -m pip install pytest==6.2.2

      - name: Install QA framework
        run: python setup.py install --user

      - name: Run unit tests
        run: python -m pytest tests/
